# Generated by Django 3.1.7 on 2021-03-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Default description', max_length=1000),
            preserve_default=False,
        ),
    ]
